title: Amit Upreti
baseline: Probably behind a computer
description: >-
  Hi, this is my blog. Here i will write about things that i find cool and
  things that might be of help to other developers. Feel free to reach if you
  want to talk
baseurl: /
canonicalurl: true
theme: hyde
date:
  format: j F Y
  timezone: Europe/Paris
pagination:
  max: 5
  path: page
output:
  formats:
    netlify_redirects:
      extension: ''
      mediatype: text/plain
virtualpages:
  _redirects:
    output: netlify_redirects
  admin:
    layout: admin/index
    title: Content Manager (Netlify CMS)
    output: html
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
